"use client";
import React from "react";
import * as _Builtin from "./_Builtin";
import * as _interactions from "./interactions";
import * as _utils from "./utils";
import _styles from "./Navbar.module.css";

const _interactionsData = JSON.parse(
  '{"events":{"e":{"id":"e","name":"","animationType":"preset","eventTypeId":"DROPDOWN_OPEN","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-48"}},"mediaQueries":["main"],"target":{"id":"fcac52bc-6c7f-416f-de56-356585a2eff3","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"fcac52bc-6c7f-416f-de56-356585a2eff3","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1662070722061},"e-2":{"id":"e-2","name":"","animationType":"preset","eventTypeId":"DROPDOWN_CLOSE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-2","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-56"}},"mediaQueries":["main"],"target":{"id":"fcac52bc-6c7f-416f-de56-356585a2eff3","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"fcac52bc-6c7f-416f-de56-356585a2eff3","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1662070722061},"e-3":{"id":"e-3","name":"","animationType":"preset","eventTypeId":"DROPDOWN_OPEN","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-3","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-46"}},"mediaQueries":["medium","small","tiny"],"target":{"id":"fcac52bc-6c7f-416f-de56-356585a2eff3","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"fcac52bc-6c7f-416f-de56-356585a2eff3","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1662070722061},"e-4":{"id":"e-4","name":"","animationType":"preset","eventTypeId":"DROPDOWN_CLOSE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-4","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-49"}},"mediaQueries":["medium","small","tiny"],"target":{"id":"fcac52bc-6c7f-416f-de56-356585a2eff3","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"fcac52bc-6c7f-416f-de56-356585a2eff3","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1662070722061},"e-295":{"id":"e-295","name":"","animationType":"preset","eventTypeId":"DROPDOWN_OPEN","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-3","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-296"}},"mediaQueries":["medium","small","tiny"],"target":{"id":"6866878b50e579d49186fb1a|e7ce0bb4-3069-6c95-eafb-d8087776fb8c","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"6866878b50e579d49186fb1a|e7ce0bb4-3069-6c95-eafb-d8087776fb8c","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1751892701615},"e-296":{"id":"e-296","name":"","animationType":"preset","eventTypeId":"DROPDOWN_CLOSE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-4","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-295"}},"mediaQueries":["medium","small","tiny"],"target":{"id":"6866878b50e579d49186fb1a|e7ce0bb4-3069-6c95-eafb-d8087776fb8c","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"6866878b50e579d49186fb1a|e7ce0bb4-3069-6c95-eafb-d8087776fb8c","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1751892701615},"e-297":{"id":"e-297","name":"","animationType":"preset","eventTypeId":"DROPDOWN_OPEN","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-298"}},"mediaQueries":["main"],"target":{"id":"6866878b50e579d49186fb1a|e7ce0bb4-3069-6c95-eafb-d8087776fb8c","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"6866878b50e579d49186fb1a|e7ce0bb4-3069-6c95-eafb-d8087776fb8c","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1751892701615},"e-298":{"id":"e-298","name":"","animationType":"preset","eventTypeId":"DROPDOWN_CLOSE","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-2","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-297"}},"mediaQueries":["main"],"target":{"id":"6866878b50e579d49186fb1a|e7ce0bb4-3069-6c95-eafb-d8087776fb8c","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"6866878b50e579d49186fb1a|e7ce0bb4-3069-6c95-eafb-d8087776fb8c","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":null,"scrollOffsetUnit":null,"delay":null,"direction":null,"effectIn":null},"createdOn":1751892701615}},"actionLists":{"a":{"id":"a","title":"Navbar dropdown 2 [Open] [Desktop]","actionItemGroups":[{"actionItems":[{"id":"a-n","actionTypeId":"STYLE_OPACITY","config":{"delay":0,"easing":"ease","duration":300,"target":{"useEventTarget":"CHILDREN","selector":".navbar-dropdown2_dropdown-list","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0e"]},"value":0,"unit":""}}]},{"actionItems":[{"id":"a-n-2","actionTypeId":"TRANSFORM_ROTATE","config":{"delay":0,"easing":"ease","duration":300,"target":{"useEventTarget":"CHILDREN","selector":".dropdown-chevron","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0d"]},"zValue":180,"xUnit":"DEG","yUnit":"DEG","zUnit":"deg"}},{"id":"a-n-3","actionTypeId":"STYLE_OPACITY","config":{"delay":0,"easing":"ease","duration":300,"target":{"useEventTarget":"CHILDREN","selector":".navbar-dropdown2_dropdown-list","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0e"]},"value":1,"unit":""}}]}],"useFirstGroupAsInitialState":true,"createdOn":1626161550593},"a-2":{"id":"a-2","title":"Navbar dropdown 2 [Close] [Desktop]","actionItemGroups":[{"actionItems":[{"id":"a-2-n","actionTypeId":"TRANSFORM_ROTATE","config":{"delay":0,"easing":"ease","duration":300,"target":{"useEventTarget":"CHILDREN","selector":".dropdown-chevron","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0d"]},"zValue":0,"xUnit":"DEG","yUnit":"DEG","zUnit":"deg"}},{"id":"a-2-n-2","actionTypeId":"STYLE_OPACITY","config":{"delay":0,"easing":"ease","duration":200,"target":{"useEventTarget":"CHILDREN","selector":".navbar-dropdown2_dropdown-list","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0e"]},"value":0,"unit":""}}]}],"useFirstGroupAsInitialState":false,"createdOn":1626161607847},"a-3":{"id":"a-3","title":"Navbar dropdown 2 [Open] [Tablet]","actionItemGroups":[{"actionItems":[{"id":"a-3-n","actionTypeId":"STYLE_SIZE","config":{"delay":0,"easing":"ease","duration":200,"target":{"useEventTarget":"CHILDREN","selector":".navbar-dropdown2_dropdown-list","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0e"]},"heightValue":0,"widthUnit":"PX","heightUnit":"px","locked":false}}]},{"actionItems":[{"id":"a-3-n-2","actionTypeId":"STYLE_SIZE","config":{"delay":0,"easing":"ease","duration":500,"target":{"useEventTarget":"CHILDREN","selector":".navbar-dropdown2_dropdown-list","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0e"]},"widthUnit":"PX","heightUnit":"AUTO","locked":false}},{"id":"a-3-n-3","actionTypeId":"TRANSFORM_ROTATE","config":{"delay":0,"easing":"ease","duration":300,"target":{"useEventTarget":"CHILDREN","selector":".dropdown-chevron","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0d"]},"zValue":180,"xUnit":"DEG","yUnit":"DEG","zUnit":"deg"}}]}],"useFirstGroupAsInitialState":true,"createdOn":1626242958157},"a-4":{"id":"a-4","title":"Navbar dropdown 2 [Close] [Tablet]","actionItemGroups":[{"actionItems":[{"id":"a-4-n","actionTypeId":"STYLE_SIZE","config":{"delay":0,"easing":"ease","duration":300,"target":{"useEventTarget":"CHILDREN","selector":".navbar-dropdown2_dropdown-list","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0e"]},"heightValue":0,"widthUnit":"PX","heightUnit":"px","locked":false}},{"id":"a-4-n-2","actionTypeId":"TRANSFORM_ROTATE","config":{"delay":0,"easing":"ease","duration":300,"target":{"useEventTarget":"CHILDREN","selector":".dropdown-chevron","selectorGuids":["0bf15f40-ba63-b927-78ec-5dd1cbdb4e0d"]},"zValue":0,"xUnit":"DEG","yUnit":"DEG","zUnit":"deg"}}]}],"useFirstGroupAsInitialState":false,"createdOn":1626242958157}},"site":{"mediaQueries":[{"key":"main","min":992,"max":10000},{"key":"medium","min":768,"max":991},{"key":"small","min":480,"max":767},{"key":"tiny","min":0,"max":479}]}}'
);

export function Navbar({
  as: _Component = _Builtin.NavbarWrapper,
  variant = "Base",
}) {
  _interactions.useInteractions(_interactionsData, _styles);

  const _styleVariantMap = {
    Base: "",
    Fixed: "w-variant-2319134e-f76a-8d65-5eb1-a5ab1dd836bc",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <_Component
      className={_utils.cx(
        _styles,
        "nav_component",
        "nav_component-blog",
        _activeStyleVariant
      )}
      tag="div"
      config={{
        animation: "default",
        collapse: "medium",
        docHeight: false,
        duration: 400,
        easing: "ease",
        easing2: "ease",
        noScroll: false,
      }}
    >
      <_Builtin.Block
        className={_utils.cx(_styles, "padding-global", _activeStyleVariant)}
        tag="div"
      >
        <_Builtin.Block
          className={_utils.cx(_styles, "nav_container", _activeStyleVariant)}
          tag="div"
        >
          <_Builtin.NavbarBrand
            className={_utils.cx(_styles, "nav_brand", _activeStyleVariant)}
            options={{
              href: "#",
            }}
          >
            <_Builtin.Image
              className={_utils.cx(_styles, "nav_logo", _activeStyleVariant)}
              loading="lazy"
              width="auto"
              height="auto"
              alt="Navbar Logo"
              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/6744629858a3ecc03b109dbe_logo.svg"
            />
          </_Builtin.NavbarBrand>
          <_Builtin.NavbarMenu
            className={_utils.cx(_styles, "nav_menu", _activeStyleVariant)}
            tag="nav"
            role="navigation"
          >
            <_Builtin.NavbarLink
              className={_utils.cx(
                _styles,
                "nav_menu_link",
                "current",
                _activeStyleVariant
              )}
              options={{
                href: "#",
              }}
            >
              {"Accueil"}
            </_Builtin.NavbarLink>
            <_Builtin.DropdownWrapper
              className={_utils.cx(
                _styles,
                "navbar-dropdown2_component",
                _activeStyleVariant
              )}
              data-w-id="fcac52bc-6c7f-416f-de56-356585a2eff3"
              tag="div"
              delay={300}
              hover={true}
            >
              <_Builtin.DropdownToggle
                className={_utils.cx(
                  _styles,
                  "navbar-dropdown2_dropdown-toggle",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <_Builtin.Link
                  className={_utils.cx(
                    _styles,
                    "link-block-6",
                    _activeStyleVariant
                  )}
                  button={false}
                  block="inline"
                  options={{
                    href: "#",
                  }}
                >
                  <_Builtin.Block tag="div">
                    {"Formations en français"}
                  </_Builtin.Block>
                </_Builtin.Link>
                <_Builtin.HtmlEmbed
                  className={_utils.cx(
                    _styles,
                    "dropdown-chevron",
                    _activeStyleVariant
                  )}
                  value="%3Csvg%20width%3D%22%20100%25%22%20height%3D%22%20100%25%22%20viewbox%3D%220%200%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%20d%3D%22M2.55806%206.29544C2.46043%206.19781%202.46043%206.03952%202.55806%205.94189L3.44195%205.058C3.53958%204.96037%203.69787%204.96037%203.7955%205.058L8.00001%209.26251L12.2045%205.058C12.3021%204.96037%2012.4604%204.96037%2012.5581%205.058L13.4419%205.94189C13.5396%206.03952%2013.5396%206.19781%2013.4419%206.29544L8.17678%2011.5606C8.07915%2011.6582%207.92086%2011.6582%207.82323%2011.5606L2.55806%206.29544Z%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                />
              </_Builtin.DropdownToggle>
              <_Builtin.DropdownList
                className={_utils.cx(
                  _styles,
                  "navbar-dropdown2_dropdown-list",
                  _activeStyleVariant
                )}
                tag="nav"
              >
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "navbar-dropdown2_container",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "navbar-dropdown2_dropdown-content",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "navbar-dropdown2_content-left",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cx(
                          _styles,
                          "navbar-dropdown2_dropdown-link-list",
                          _activeStyleVariant
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "text-color-blue",
                            "text-weight-bold",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-_8292e71e-6f39-42a1-85f9-20482d196f88-63dfdea9"
                          )}
                          tag="div"
                        >
                          {"Selon votre situation"}
                        </_Builtin.Block>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "/formations?age=Jeunes et étudiants",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Jeunes et etudiants"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"A partir de 16 ans"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-c4f2e4a0-decc-8131-e72b-a48568457313-63dfdea9"
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "/formations?age=Adultes",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Adultes"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"Adultes en poste"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-_454924f7-5ecd-1771-03d6-679f386c30c8-63dfdea9"
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "#",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Professionnels etentreprises"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"Salariés et indépendants"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-d4e19681-6cdb-ea38-6736-6ecbb93949d3-63dfdea9"
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "/formations?age=Eligible CPF",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Eligible au CPF"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"Prise en charge jusqu'à 100%"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-a7770eb6-6b0b-9991-6b5d-e41157bd90e5-63dfdea9"
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "#",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"TCF"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"Prise en charge jusqu'à 100%"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className={_utils.cx(
                          _styles,
                          "navbar-dropdown2_dropdown-link-list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-_0a4367b6-b59e-4e55-e8ff-f6fe9f03de53-63dfdea9"
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "text-color-blue",
                            "text-weight-bold",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-_0a4367b6-b59e-4e55-e8ff-f6fe9f03de54-63dfdea9"
                          )}
                          tag="div"
                        >
                          {"Examens de français et certifications"}
                        </_Builtin.Block>
                        <_Builtin.NotSupported _atom="DynamoWrapper" />
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "navmenu-divider",
                        _activeStyleVariant
                      )}
                      tag="div"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "spacer-small",
                        _activeStyleVariant
                      )}
                      tag="div"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "display-flex",
                        "navmenu-display_flex",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cx(
                          _styles,
                          "text-content",
                          _activeStyleVariant
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "text-size-small",
                            "text-color-blue",
                            "text-weight-bold",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {
                            " Vous souhaitez accéder à l'intégralité de nos formations ?"
                          }
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "button",
                          "is-icon",
                          _activeStyleVariant
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "text-weight-medium",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Voir toutes les formations"}
                        </_Builtin.Block>
                        <_Builtin.Image
                          className={_utils.cx(
                            _styles,
                            "button-icon",
                            _activeStyleVariant
                          )}
                          loading="lazy"
                          width="auto"
                          height="auto"
                          alt="Right Arrow Icon"
                          src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/67449dc868c6e76c07f82653_arrow-narrow-right.svg"
                        />
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.DropdownList>
            </_Builtin.DropdownWrapper>
            <_Builtin.DropdownWrapper
              className={_utils.cx(
                _styles,
                "navbar-dropdown2_component",
                _activeStyleVariant
              )}
              data-w-id="e7ce0bb4-3069-6c95-eafb-d8087776fb8c"
              tag="div"
              delay={300}
              hover={true}
            >
              <_Builtin.DropdownToggle
                className={_utils.cx(
                  _styles,
                  "navbar-dropdown2_dropdown-toggle",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <_Builtin.Link
                  className={_utils.cx(
                    _styles,
                    "link-block-5",
                    _activeStyleVariant
                  )}
                  button={false}
                  block="inline"
                  options={{
                    href: "#",
                  }}
                >
                  <_Builtin.Block tag="div">
                    {"Formations civiques"}
                  </_Builtin.Block>
                </_Builtin.Link>
                <_Builtin.HtmlEmbed
                  className={_utils.cx(
                    _styles,
                    "dropdown-chevron",
                    _activeStyleVariant
                  )}
                  value="%3Csvg%20width%3D%22%20100%25%22%20height%3D%22%20100%25%22%20viewbox%3D%220%200%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%20d%3D%22M2.55806%206.29544C2.46043%206.19781%202.46043%206.03952%202.55806%205.94189L3.44195%205.058C3.53958%204.96037%203.69787%204.96037%203.7955%205.058L8.00001%209.26251L12.2045%205.058C12.3021%204.96037%2012.4604%204.96037%2012.5581%205.058L13.4419%205.94189C13.5396%206.03952%2013.5396%206.19781%2013.4419%206.29544L8.17678%2011.5606C8.07915%2011.6582%207.92086%2011.6582%207.82323%2011.5606L2.55806%206.29544Z%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                />
              </_Builtin.DropdownToggle>
              <_Builtin.DropdownList
                className={_utils.cx(
                  _styles,
                  "navbar-dropdown2_dropdown-list",
                  _activeStyleVariant
                )}
                tag="nav"
              >
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "navbar-dropdown2_container",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "navbar-dropdown2_dropdown-content",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "navbar-dropdown2_content-left",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cx(
                          _styles,
                          "navbar-dropdown2_dropdown-link-list",
                          _activeStyleVariant
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "text-color-blue",
                            "text-weight-bold",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-e7ce0bb4-3069-6c95-eafb-d8087776fb97-63dfdea9"
                          )}
                          tag="div"
                        >
                          {"Selon votre situation"}
                        </_Builtin.Block>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "/formations?age=Jeunes et étudiants",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Jeunes et etudiants"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"A partir de 16 ans"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-e7ce0bb4-3069-6c95-eafb-d8087776fba1-63dfdea9"
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "/formations?age=Adultes",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Adultes"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"Adultes en poste"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-e7ce0bb4-3069-6c95-eafb-d8087776fba9-63dfdea9"
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "#",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Professionnels etentreprises"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"Salariés et indépendants"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                        <_Builtin.Link
                          className={_utils.cx(
                            _styles,
                            "navbar-dropdown2_dropdown-link",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-e7ce0bb4-3069-6c95-eafb-d8087776fbb1-63dfdea9"
                          )}
                          button={false}
                          block="inline"
                          options={{
                            href: "/formations?age=Eligible CPF",
                          }}
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_icon-wrapper",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Image
                              className={_utils.cx(
                                _styles,
                                "icon-height-xsmall",
                                _activeStyleVariant
                              )}
                              width="auto"
                              height="auto"
                              loading="lazy"
                              alt=""
                              src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/674dc62b5d7840e356d8b78a_france%20icon.svg"
                            />
                          </_Builtin.Block>
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "navbar5_item-right",
                              _activeStyleVariant
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "text-weight-medium",
                                "text-color-gray",
                                "text-size-small",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Eligible au CPF"}
                            </_Builtin.Block>
                            <_Builtin.Paragraph
                              className={_utils.cx(
                                _styles,
                                "text-color-gray",
                                "text-size-xsmall",
                                "text-weight-medium",
                                _activeStyleVariant
                              )}
                            >
                              {"Prise en charge jusqu'à 100%"}
                            </_Builtin.Paragraph>
                          </_Builtin.Block>
                        </_Builtin.Link>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className={_utils.cx(
                          _styles,
                          "navbar-dropdown2_dropdown-link-list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-e7ce0bb4-3069-6c95-eafb-d8087776fbb9-63dfdea9"
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "text-color-blue",
                            "text-weight-bold",
                            _activeStyleVariant
                          )}
                          id={_utils.cx(
                            _styles,
                            "w-node-e7ce0bb4-3069-6c95-eafb-d8087776fbba-63dfdea9"
                          )}
                          tag="div"
                        >
                          {"Examens de français et certifications"}
                        </_Builtin.Block>
                        <_Builtin.NotSupported _atom="DynamoWrapper" />
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "navmenu-divider",
                        _activeStyleVariant
                      )}
                      tag="div"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "spacer-small",
                        _activeStyleVariant
                      )}
                      tag="div"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "display-flex",
                        "navmenu-display_flex",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cx(
                          _styles,
                          "text-content",
                          _activeStyleVariant
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "text-size-small",
                            "text-color-blue",
                            "text-weight-bold",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {
                            " Vous souhaitez accéder à l'intégralité de nos formations ?"
                          }
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "button",
                          "is-icon",
                          _activeStyleVariant
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "text-weight-medium",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Voir toutes les formations"}
                        </_Builtin.Block>
                        <_Builtin.Image
                          className={_utils.cx(
                            _styles,
                            "button-icon",
                            _activeStyleVariant
                          )}
                          loading="lazy"
                          width="auto"
                          height="auto"
                          alt="Right Arrow Icon"
                          src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/67449dc868c6e76c07f82653_arrow-narrow-right.svg"
                        />
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.DropdownList>
            </_Builtin.DropdownWrapper>
            <_Builtin.NavbarLink
              className={_utils.cx(
                _styles,
                "nav_menu_link",
                _activeStyleVariant
              )}
              options={{
                href: "#",
              }}
            >
              {"Entreprises"}
            </_Builtin.NavbarLink>
            <_Builtin.NavbarLink
              className={_utils.cx(
                _styles,
                "nav_menu_link",
                _activeStyleVariant
              )}
              options={{
                href: "#",
              }}
            >
              {"Financements"}
            </_Builtin.NavbarLink>
            <_Builtin.NavbarLink
              className={_utils.cx(
                _styles,
                "nav_menu_link",
                _activeStyleVariant
              )}
              options={{
                href: "#",
              }}
            >
              {"Ressources"}
            </_Builtin.NavbarLink>
            <_Builtin.Block
              className={_utils.cx(
                _styles,
                "navmenu_button-wrapper",
                "tablet-navmenu_buttons",
                _activeStyleVariant
              )}
              tag="div"
            >
              <_Builtin.Link
                className={_utils.cx(
                  _styles,
                  "navbar-icon_wrapper",
                  _activeStyleVariant
                )}
                button={false}
                block="inline"
                options={{
                  href: "#",
                }}
              >
                <_Builtin.Image
                  className={_utils.cx(
                    _styles,
                    "navbar-icon",
                    _activeStyleVariant
                  )}
                  loading="lazy"
                  width="auto"
                  height="auto"
                  alt="Book Icon"
                  src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/67449b1aadc4f71bf54ba058_book-open-01.svg"
                />
              </_Builtin.Link>
              <_Builtin.Link
                className={_utils.cx(
                  _styles,
                  "navbar-icon_wrapper",
                  _activeStyleVariant
                )}
                button={false}
                block="inline"
                options={{
                  href: "#",
                }}
              >
                <_Builtin.Image
                  className={_utils.cx(
                    _styles,
                    "navbar-icon",
                    _activeStyleVariant
                  )}
                  loading="lazy"
                  width="auto"
                  height="auto"
                  alt="Search Icon"
                  src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/67449af0c06e337888522ab5_search-sm.svg"
                />
              </_Builtin.Link>
              <_Builtin.Link
                className={_utils.cx(
                  _styles,
                  "button",
                  "is-icon",
                  _activeStyleVariant
                )}
                button={false}
                block="inline"
                options={{
                  href: "#",
                }}
              >
                <_Builtin.Image
                  className={_utils.cx(
                    _styles,
                    "button-icon",
                    _activeStyleVariant
                  )}
                  loading="lazy"
                  width="auto"
                  height="auto"
                  alt="Phone Call Icon"
                  src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/67449a8e9a613ef2d1faec3b_phone-call-01%20white.svg"
                />
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "text-weight-medium",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  {"01 23 45 33 44"}
                </_Builtin.Block>
              </_Builtin.Link>
            </_Builtin.Block>
          </_Builtin.NavbarMenu>
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "navmenu_button-wrapper",
              _activeStyleVariant
            )}
            tag="div"
          >
            <_Builtin.Link
              className={_utils.cx(
                _styles,
                "navbar-icon_wrapper",
                _activeStyleVariant
              )}
              button={false}
              block="inline"
              options={{
                href: "#",
              }}
            >
              <_Builtin.Image
                className={_utils.cx(
                  _styles,
                  "navbar-icon",
                  _activeStyleVariant
                )}
                loading="lazy"
                width="auto"
                height="auto"
                alt="Book Icon"
                src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/67449b1aadc4f71bf54ba058_book-open-01.svg"
              />
            </_Builtin.Link>
            <_Builtin.Link
              className={_utils.cx(
                _styles,
                "button",
                "is-icon",
                _activeStyleVariant
              )}
              button={false}
              block="inline"
              options={{
                href: "tel:+33189717096",
              }}
            >
              <_Builtin.Image
                className={_utils.cx(
                  _styles,
                  "button-icon",
                  _activeStyleVariant
                )}
                loading="lazy"
                width="auto"
                height="auto"
                alt="Phone Call Icon"
                src="https://cdn.prod.website-files.com/67444b8dcde8d2a8775775ed/67449a8e9a613ef2d1faec3b_phone-call-01%20white.svg"
              />
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "text-weight-medium",
                  _activeStyleVariant
                )}
                tag="div"
              >
                {"+33189717096"}
              </_Builtin.Block>
            </_Builtin.Link>
          </_Builtin.Block>
          <_Builtin.NavbarButton
            className={_utils.cx(_styles, "nav_button", _activeStyleVariant)}
            tag="div"
          >
            <_Builtin.Icon
              className={_utils.cx(_styles, "icon-2", _activeStyleVariant)}
              widget={{
                type: "icon",
                icon: "nav-menu",
              }}
            />
          </_Builtin.NavbarButton>
        </_Builtin.Block>
      </_Builtin.Block>
    </_Component>
  );
}
